// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: base.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -----------------servicio-----------------
type ResultadoGuardar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valor int32  `protobuf:"varint,1,opt,name=Valor,proto3" json:"Valor,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *ResultadoGuardar) Reset() {
	*x = ResultadoGuardar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultadoGuardar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoGuardar) ProtoMessage() {}

func (x *ResultadoGuardar) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoGuardar.ProtoReflect.Descriptor instead.
func (*ResultadoGuardar) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{0}
}

func (x *ResultadoGuardar) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *ResultadoGuardar) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResultadoObtenerEliminar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clave string `protobuf:"bytes,1,opt,name=Clave,proto3" json:"Clave,omitempty"`
	Valor string `protobuf:"bytes,2,opt,name=Valor,proto3" json:"Valor,omitempty"`
	Error string `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *ResultadoObtenerEliminar) Reset() {
	*x = ResultadoObtenerEliminar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultadoObtenerEliminar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoObtenerEliminar) ProtoMessage() {}

func (x *ResultadoObtenerEliminar) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoObtenerEliminar.ProtoReflect.Descriptor instead.
func (*ResultadoObtenerEliminar) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{1}
}

func (x *ResultadoObtenerEliminar) GetClave() string {
	if x != nil {
		return x.Clave
	}
	return ""
}

func (x *ResultadoObtenerEliminar) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

func (x *ResultadoObtenerEliminar) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ParametroGuardar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clave string `protobuf:"bytes,1,opt,name=Clave,proto3" json:"Clave,omitempty"`
	Valor string `protobuf:"bytes,2,opt,name=Valor,proto3" json:"Valor,omitempty"`
}

func (x *ParametroGuardar) Reset() {
	*x = ParametroGuardar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParametroGuardar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParametroGuardar) ProtoMessage() {}

func (x *ParametroGuardar) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParametroGuardar.ProtoReflect.Descriptor instead.
func (*ParametroGuardar) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{2}
}

func (x *ParametroGuardar) GetClave() string {
	if x != nil {
		return x.Clave
	}
	return ""
}

func (x *ParametroGuardar) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

type ParametroObtenerEliminar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clave string `protobuf:"bytes,1,opt,name=Clave,proto3" json:"Clave,omitempty"`
}

func (x *ParametroObtenerEliminar) Reset() {
	*x = ParametroObtenerEliminar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParametroObtenerEliminar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParametroObtenerEliminar) ProtoMessage() {}

func (x *ParametroObtenerEliminar) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParametroObtenerEliminar.ProtoReflect.Descriptor instead.
func (*ParametroObtenerEliminar) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{3}
}

func (x *ParametroObtenerEliminar) GetClave() string {
	if x != nil {
		return x.Clave
	}
	return ""
}

var File_base_proto protoreflect.FileDescriptor

var file_base_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x22, 0x3e, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x47,
	0x75, 0x61, 0x72, 0x64, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x5c, 0x0a, 0x18, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x4f,
	0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x43, 0x6c, 0x61, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43,
	0x6c, 0x61, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x3e, 0x0a, 0x10, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x72, 0x6f, 0x47, 0x75, 0x61,
	0x72, 0x64, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x76, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x6c, 0x61, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x6f, 0x72,
	0x22, 0x30, 0x0a, 0x18, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x72, 0x6f, 0x4f, 0x62, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x6c, 0x61, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x6c, 0x61,
	0x76, 0x65, 0x32, 0xd8, 0x01, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x67,
	0x75, 0x61, 0x72, 0x64, 0x61, 0x72, 0x12, 0x16, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x72, 0x6f, 0x47, 0x75, 0x61, 0x72, 0x64, 0x61, 0x72, 0x1a, 0x16,
	0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x47,
	0x75, 0x61, 0x72, 0x64, 0x61, 0x72, 0x12, 0x49, 0x0a, 0x07, 0x6f, 0x62, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x12, 0x1e, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x72, 0x6f, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61,
	0x72, 0x1a, 0x1e, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61,
	0x64, 0x6f, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61,
	0x72, 0x12, 0x4a, 0x0a, 0x08, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x12, 0x1e, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x72, 0x6f, 0x4f, 0x62,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x1a, 0x1e, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x4f, 0x62,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x42, 0x0a, 0x5a,
	0x08, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_base_proto_rawDescOnce sync.Once
	file_base_proto_rawDescData = file_base_proto_rawDesc
)

func file_base_proto_rawDescGZIP() []byte {
	file_base_proto_rawDescOnce.Do(func() {
		file_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_proto_rawDescData)
	})
	return file_base_proto_rawDescData
}

var file_base_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_base_proto_goTypes = []interface{}{
	(*ResultadoGuardar)(nil),         // 0: base.ResultadoGuardar
	(*ResultadoObtenerEliminar)(nil), // 1: base.ResultadoObtenerEliminar
	(*ParametroGuardar)(nil),         // 2: base.ParametroGuardar
	(*ParametroObtenerEliminar)(nil), // 3: base.ParametroObtenerEliminar
}
var file_base_proto_depIdxs = []int32{
	2, // 0: base.Base.guardar:input_type -> base.ParametroGuardar
	3, // 1: base.Base.obtener:input_type -> base.ParametroObtenerEliminar
	3, // 2: base.Base.eliminar:input_type -> base.ParametroObtenerEliminar
	0, // 3: base.Base.guardar:output_type -> base.ResultadoGuardar
	1, // 4: base.Base.obtener:output_type -> base.ResultadoObtenerEliminar
	1, // 5: base.Base.eliminar:output_type -> base.ResultadoObtenerEliminar
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_proto_init() }
func file_base_proto_init() {
	if File_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultadoGuardar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultadoObtenerEliminar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParametroGuardar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParametroObtenerEliminar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_proto_goTypes,
		DependencyIndexes: file_base_proto_depIdxs,
		MessageInfos:      file_base_proto_msgTypes,
	}.Build()
	File_base_proto = out.File
	file_base_proto_rawDesc = nil
	file_base_proto_goTypes = nil
	file_base_proto_depIdxs = nil
}
